_commit: 0a6dd28
_src_path: /Users/ian/projects/scaffolding/go-template
author_email: ian.furst@gmail.com
author_name: Ian Furst
go_version: "1.26"
module_path: github.com/ianeff/gooser
project_name: gooser
project_type: project
